---
services:
  weaviate_api:
    # image: navanitdock/test_1:01@sha256:1c596312cf1268b93b3d8011f0030a87f17284e93f482f7faf08f3a9c4d55583
    image: 5f7b9a685921
    restart: unless-stopped
    ports:
      - "8050:8050"
    user: "1000:1000"
    environment:
      HOME: '/src'
      TMPDIR: '/src/tmp'
    entrypoint:
      - /bin/sh
      - -c
      - "python3 main_api.py"
    volumes:
      - ./src:/src
      - /mnt/e/win_python/hb_model/gte-large-en-v1.5:/mnt/gte-large-en-v1.5
  
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.5
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
     - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'


